#!/usr/bin/env bash
# Home page "Featured Collections" — now fully manageable from the admin.
#
#   Heading area (small line above, big heading, intro text, links):
#     Admin > Content > Blocks > "home_featured_collections"  (created for you, published,
#     with the heading the section always had). In the block editor:
#       - a paragraph ABOVE the heading  -> the small uppercase line
#       - the Heading 2                  -> the big title (bold/italic words work)
#       - a paragraph BELOW the heading  -> intro text; links in it are styled as links
#     Set the block to Draft (or delete it) to go back to the original heading.
#
#   The cards (image, text, button):
#     Admin > Content > Banners, group "Promo" — each active Promo banner is one card:
#       image = the banner image, Title, Subtitle, Button Text (NEW: was ignored before —
#       blank shows "Explore →"), Button Link, Position (order), Active.
#     Title and Subtitle accept simple formatting: <br> new line, <b>, <em>, <u> (anything
#     else is stripped for safety).
#     Until you add at least one active Promo banner, the section shows the 3 built-in demo
#     cards. Before this change the section ignored Promo banners unless a Promo Banner Grid
#     widget had been placed — now the banners are picked up automatically.
#
#   Also fixed: the colour backdrops offered in the banner form ("Blue → Indigo" etc.) were
#   not being generated by the storefront, so a banner without an image could show a blank
#   backdrop; they all render now.
#
# One data migration (creates the header block; never overwrites an existing one).
# No new permission.
#
# Run from the repo root, after `git pull`: ./deploy/deploy-featured-collections.sh
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

COMPOSE="docker compose -f docker-compose.prod.yml --env-file .env.production"

echo "==> Rebuilding api (needed to run the migration)"
$COMPOSE up -d --build api
if [ $? -ne 0 ]; then
  echo "!! api build/restart failed — see the output above" >&2
  exit 1
fi

echo "==> Creating the home_featured_collections content block"
$COMPOSE exec api npm run migrate:deploy
if [ $? -ne 0 ]; then
  echo "!! migration failed — see the output above, copy it back" >&2
  exit 1
fi

echo "==> Rebuilding admin (banner form hints)"
$COMPOSE up -d --build admin
if [ $? -ne 0 ]; then
  echo "!! admin build/restart failed — see the output above" >&2
  exit 1
fi

echo "==> Rebuilding storefront (Featured Collections)"
$COMPOSE up -d --build storefront
if [ $? -ne 0 ]; then
  echo "!! storefront build/restart failed — see the output above" >&2
  exit 1
fi

echo
echo "==> Done. Heading: Admin > Content > Blocks > home_featured_collections."
echo "Cards: Admin > Content > Banners (group Promo)."
