-- Foundation migration (Store + Catalog core). Assembled: uuidv7() -> tables -> raw SQL.
-- See plan/02-prisma-schema-and-migrations.md §6.

-- === uuidv7() (must exist before CREATE TABLE defaults reference it) ===
CREATE OR REPLACE FUNCTION uuidv7() RETURNS uuid AS $$
DECLARE
  ts_ms      bigint := (extract(epoch FROM clock_timestamp()) * 1000)::bigint;
  uuid_bytes bytea  := uuid_send(gen_random_uuid());
BEGIN
  uuid_bytes := overlay(uuid_bytes placing substring(int8send(ts_ms) FROM 3) FROM 1 FOR 6);
  uuid_bytes := set_byte(uuid_bytes, 6, (get_byte(uuid_bytes, 6) & 15) | 112);
  uuid_bytes := set_byte(uuid_bytes, 8, (get_byte(uuid_bytes, 8) & 63) | 128);
  RETURN encode(uuid_bytes, 'hex')::uuid;
END;
$$ LANGUAGE plpgsql VOLATILE;

-- === Base tables / enums / indexes (generated by `prisma migrate diff`) ===
-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "btree_gin";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "citext";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "ltree";

-- CreateExtension
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- CreateEnum
CREATE TYPE "ScopeType" AS ENUM ('GLOBAL', 'WEBSITE', 'STORE', 'STORE_VIEW');

-- CreateEnum
CREATE TYPE "StoreViewStatus" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "AttributeScope" AS ENUM ('GLOBAL', 'WEBSITE', 'STORE_VIEW');

-- CreateEnum
CREATE TYPE "AttributeDataType" AS ENUM ('TEXT', 'TEXTAREA', 'NUMBER', 'DECIMAL', 'BOOLEAN', 'DATE', 'DATETIME', 'COLOR', 'SELECT', 'MULTISELECT', 'IMAGE', 'FILE', 'URL', 'EMAIL', 'PHONE', 'JSON', 'RICHTEXT', 'REF_PRODUCT', 'REF_CATEGORY', 'REF_BRAND', 'REF_CMS', 'REF_COLLECTION', 'REF_CUSTOMER');

-- CreateEnum
CREATE TYPE "AttributeInputType" AS ENUM ('TEXT', 'TEXTAREA', 'NUMBER', 'DECIMAL', 'SWITCH', 'DATE', 'DATETIME', 'COLOR_PICKER', 'DROPDOWN', 'MULTISELECT', 'IMAGE_PICKER', 'FILE_UPLOAD', 'RICHTEXT', 'URL', 'EMAIL', 'PHONE', 'JSON_EDITOR', 'REFERENCE');

-- CreateEnum
CREATE TYPE "ReferenceKind" AS ENUM ('PRODUCT', 'CATEGORY', 'BRAND', 'CMS', 'COLLECTION', 'CUSTOMER');

-- CreateEnum
CREATE TYPE "ProductType" AS ENUM ('SIMPLE', 'CONFIGURABLE', 'BUNDLE', 'DIGITAL', 'VIRTUAL');

-- CreateEnum
CREATE TYPE "ProductStatus" AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "ProductVisibility" AS ENUM ('NOT_VISIBLE', 'CATALOG', 'SEARCH', 'BOTH');

-- CreateEnum
CREATE TYPE "VariantStatus" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "ProductLinkType" AS ENUM ('RELATED', 'CROSS_SELL', 'UP_SELL');

-- CreateEnum
CREATE TYPE "BundlePriceType" AS ENUM ('FIXED', 'DYNAMIC');

-- CreateEnum
CREATE TYPE "CategoryType" AS ENUM ('MANUAL', 'DYNAMIC');

-- CreateEnum
CREATE TYPE "CategorySortMode" AS ENUM ('POSITION', 'NAME', 'PRICE', 'NEWEST');

-- CreateEnum
CREATE TYPE "MediaKind" AS ENUM ('IMAGE', 'VIDEO', 'DOCUMENT', 'MODEL3D');

-- CreateEnum
CREATE TYPE "ProductMediaRole" AS ENUM ('GALLERY', 'THUMBNAIL', 'SWATCH', 'VIDEO', 'DOCUMENT');

-- CreateEnum
CREATE TYPE "MetafieldOwnerType" AS ENUM ('PRODUCT', 'VARIANT', 'CATEGORY', 'CUSTOMER', 'ORDER');

-- CreateTable
CREATE TABLE "attribute" (
    "id" BIGSERIAL NOT NULL,
    "code" CITEXT NOT NULL,
    "label" TEXT NOT NULL,
    "data_type" "AttributeDataType" NOT NULL,
    "input_type" "AttributeInputType" NOT NULL,
    "is_required" BOOLEAN NOT NULL DEFAULT false,
    "is_searchable" BOOLEAN NOT NULL DEFAULT false,
    "is_filterable" BOOLEAN NOT NULL DEFAULT false,
    "is_comparable" BOOLEAN NOT NULL DEFAULT false,
    "is_sortable" BOOLEAN NOT NULL DEFAULT false,
    "is_visible_pdp" BOOLEAN NOT NULL DEFAULT true,
    "is_visible_plp" BOOLEAN NOT NULL DEFAULT false,
    "used_in_search" BOOLEAN NOT NULL DEFAULT false,
    "used_in_layered_nav" BOOLEAN NOT NULL DEFAULT false,
    "is_variant_forming" BOOLEAN NOT NULL DEFAULT false,
    "scope" "AttributeScope" NOT NULL DEFAULT 'GLOBAL',
    "validation_rules" JSONB NOT NULL DEFAULT '{}',
    "default_value" JSONB,
    "placeholder" TEXT,
    "tooltip" TEXT,
    "is_translatable" BOOLEAN NOT NULL DEFAULT false,
    "reference_type" "ReferenceKind",
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "attribute_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "attribute_option" (
    "id" BIGSERIAL NOT NULL,
    "attribute_id" BIGINT NOT NULL,
    "value" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "swatch" TEXT,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "attribute_option_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "attribute_label" (
    "id" BIGSERIAL NOT NULL,
    "attribute_id" BIGINT NOT NULL,
    "store_view_id" BIGINT NOT NULL,
    "label" TEXT NOT NULL,

    CONSTRAINT "attribute_label_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "attribute_set" (
    "id" BIGSERIAL NOT NULL,
    "code" CITEXT NOT NULL,
    "name" TEXT NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "attribute_set_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "attribute_set_group" (
    "id" BIGSERIAL NOT NULL,
    "attribute_set_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "attribute_set_group_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "attribute_set_attribute" (
    "id" BIGSERIAL NOT NULL,
    "attribute_set_id" BIGINT NOT NULL,
    "group_id" BIGINT NOT NULL,
    "attribute_id" BIGINT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "is_required_override" BOOLEAN,

    CONSTRAINT "attribute_set_attribute_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product" (
    "id" BIGSERIAL NOT NULL,
    "public_id" UUID NOT NULL DEFAULT uuidv7(),
    "type" "ProductType" NOT NULL,
    "sku" CITEXT NOT NULL,
    "attribute_set_id" BIGINT NOT NULL,
    "status" "ProductStatus" NOT NULL DEFAULT 'DRAFT',
    "visibility" "ProductVisibility" NOT NULL DEFAULT 'BOTH',
    "tax_class_id" BIGINT,
    "weight" DECIMAL(12,4),
    "is_digital" BOOLEAN NOT NULL DEFAULT false,
    "is_virtual" BOOLEAN NOT NULL DEFAULT false,
    "has_variants" BOOLEAN NOT NULL DEFAULT false,
    "name_default" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_variant" (
    "id" BIGSERIAL NOT NULL,
    "public_id" UUID NOT NULL DEFAULT uuidv7(),
    "product_id" BIGINT NOT NULL,
    "sku" CITEXT NOT NULL,
    "barcode" TEXT,
    "weight" DECIMAL(12,4),
    "position" INTEGER NOT NULL DEFAULT 0,
    "status" "VariantStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "product_variant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "variant_axis_value" (
    "id" BIGSERIAL NOT NULL,
    "variant_id" BIGINT NOT NULL,
    "attribute_id" BIGINT NOT NULL,
    "option_id" BIGINT NOT NULL,

    CONSTRAINT "variant_axis_value_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_store_view" (
    "id" BIGSERIAL NOT NULL,
    "product_id" BIGINT NOT NULL,
    "store_view_id" BIGINT NOT NULL,
    "is_visible" BOOLEAN NOT NULL DEFAULT true,
    "status_override" "ProductStatus",

    CONSTRAINT "product_store_view_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_link" (
    "id" BIGSERIAL NOT NULL,
    "product_id" BIGINT NOT NULL,
    "linked_product_id" BIGINT NOT NULL,
    "link_type" "ProductLinkType" NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "product_link_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_bundle_item" (
    "id" BIGSERIAL NOT NULL,
    "bundle_product_id" BIGINT NOT NULL,
    "component_product_id" BIGINT NOT NULL,
    "group_label" TEXT,
    "qty" INTEGER NOT NULL DEFAULT 1,
    "is_optional" BOOLEAN NOT NULL DEFAULT false,
    "price_type" "BundlePriceType" NOT NULL DEFAULT 'DYNAMIC',
    "user_defined_qty" BOOLEAN NOT NULL DEFAULT false,
    "sort_order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "product_bundle_item_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_attribute_value" (
    "id" BIGSERIAL NOT NULL,
    "product_id" BIGINT NOT NULL,
    "attribute_id" BIGINT NOT NULL,
    "scope" "ScopeType" NOT NULL DEFAULT 'GLOBAL',
    "website_id" BIGINT,
    "store_id" BIGINT,
    "store_view_id" BIGINT,
    "value_text" TEXT,
    "value_int" BIGINT,
    "value_decimal" DECIMAL(18,4),
    "value_datetime" TIMESTAMPTZ(6),
    "value_json" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "product_attribute_value_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "category" (
    "id" BIGSERIAL NOT NULL,
    "public_id" UUID NOT NULL DEFAULT uuidv7(),
    "parent_id" BIGINT,
    "path" ltree,
    "type" "CategoryType" NOT NULL DEFAULT 'MANUAL',
    "landing_page_cms_id" BIGINT,
    "sort_mode" "CategorySortMode" NOT NULL DEFAULT 'POSITION',
    "position" INTEGER NOT NULL DEFAULT 0,
    "name_default" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "category_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "category_closure" (
    "ancestor_id" BIGINT NOT NULL,
    "descendant_id" BIGINT NOT NULL,
    "depth" INTEGER NOT NULL,

    CONSTRAINT "category_closure_pkey" PRIMARY KEY ("ancestor_id","descendant_id")
);

-- CreateTable
CREATE TABLE "category_rule" (
    "id" BIGSERIAL NOT NULL,
    "category_id" BIGINT NOT NULL,
    "rule" JSONB NOT NULL DEFAULT '{}',
    "match_type" TEXT NOT NULL DEFAULT 'all',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "category_rule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_category" (
    "product_id" BIGINT NOT NULL,
    "category_id" BIGINT NOT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "is_dynamic" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "product_category_pkey" PRIMARY KEY ("product_id","category_id")
);

-- CreateTable
CREATE TABLE "media_asset" (
    "id" BIGSERIAL NOT NULL,
    "public_id" UUID NOT NULL DEFAULT uuidv7(),
    "storage_key" TEXT NOT NULL,
    "mime_type" TEXT NOT NULL,
    "bytes" BIGINT NOT NULL,
    "width" INTEGER,
    "height" INTEGER,
    "duration" INTEGER,
    "checksum" TEXT,
    "alt_default" TEXT,
    "kind" "MediaKind" NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "media_asset_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "media_transform" (
    "id" BIGSERIAL NOT NULL,
    "asset_id" BIGINT NOT NULL,
    "variant" TEXT NOT NULL,
    "storage_key" TEXT NOT NULL,
    "width" INTEGER,
    "height" INTEGER,

    CONSTRAINT "media_transform_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_media" (
    "id" BIGSERIAL NOT NULL,
    "product_id" BIGINT NOT NULL,
    "variant_id" BIGINT,
    "asset_id" BIGINT NOT NULL,
    "role" "ProductMediaRole" NOT NULL DEFAULT 'GALLERY',
    "position" INTEGER NOT NULL DEFAULT 0,
    "store_view_id" BIGINT,
    "alt_override" TEXT,

    CONSTRAINT "product_media_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "metafield_definition" (
    "id" BIGSERIAL NOT NULL,
    "owner_type" "MetafieldOwnerType" NOT NULL,
    "namespace" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "data_type" "AttributeDataType" NOT NULL,
    "validation" JSONB NOT NULL DEFAULT '{}',
    "scope" "AttributeScope" NOT NULL DEFAULT 'GLOBAL',
    "is_visible" BOOLEAN NOT NULL DEFAULT true,
    "group_name" TEXT,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "metafield_definition_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "metafield_value" (
    "id" BIGSERIAL NOT NULL,
    "definition_id" BIGINT NOT NULL,
    "owner_id" BIGINT NOT NULL,
    "scope" "ScopeType" NOT NULL DEFAULT 'GLOBAL',
    "website_id" BIGINT,
    "store_id" BIGINT,
    "store_view_id" BIGINT,
    "language_id" BIGINT,
    "value" JSONB NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,

    CONSTRAINT "metafield_value_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "currency" (
    "code" CHAR(3) NOT NULL,
    "symbol" TEXT NOT NULL,
    "minor_units" INTEGER NOT NULL DEFAULT 2,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "currency_pkey" PRIMARY KEY ("code")
);

-- CreateTable
CREATE TABLE "language" (
    "id" BIGSERIAL NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "native_name" TEXT NOT NULL,
    "is_rtl" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "language_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "theme" (
    "id" BIGSERIAL NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "config" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "theme_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "website" (
    "id" BIGSERIAL NOT NULL,
    "public_id" UUID NOT NULL DEFAULT uuidv7(),
    "code" CITEXT NOT NULL,
    "name" TEXT NOT NULL,
    "base_currency" CHAR(3) NOT NULL,
    "default_store_id" BIGINT,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "website_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "store" (
    "id" BIGSERIAL NOT NULL,
    "public_id" UUID NOT NULL DEFAULT uuidv7(),
    "website_id" BIGINT NOT NULL,
    "code" CITEXT NOT NULL,
    "name" TEXT NOT NULL,
    "root_category_id" BIGINT,
    "default_store_view_id" BIGINT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "store_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "store_view" (
    "id" BIGSERIAL NOT NULL,
    "public_id" UUID NOT NULL DEFAULT uuidv7(),
    "store_id" BIGINT NOT NULL,
    "code" CITEXT NOT NULL,
    "language_id" BIGINT NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "theme_id" BIGINT,
    "is_rtl" BOOLEAN NOT NULL DEFAULT false,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "status" "StoreViewStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_by" BIGINT,
    "updated_by" BIGINT,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "store_view_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "attribute_code_key" ON "attribute"("code");

-- CreateIndex
CREATE INDEX "attribute_deleted_at_idx" ON "attribute"("deleted_at");

-- CreateIndex
CREATE INDEX "attribute_is_filterable_idx" ON "attribute"("is_filterable");

-- CreateIndex
CREATE INDEX "attribute_is_variant_forming_idx" ON "attribute"("is_variant_forming");

-- CreateIndex
CREATE INDEX "attribute_option_attribute_id_sort_order_idx" ON "attribute_option"("attribute_id", "sort_order");

-- CreateIndex
CREATE UNIQUE INDEX "attribute_option_attribute_id_value_key" ON "attribute_option"("attribute_id", "value");

-- CreateIndex
CREATE UNIQUE INDEX "attribute_label_attribute_id_store_view_id_key" ON "attribute_label"("attribute_id", "store_view_id");

-- CreateIndex
CREATE UNIQUE INDEX "attribute_set_code_key" ON "attribute_set"("code");

-- CreateIndex
CREATE INDEX "attribute_set_deleted_at_idx" ON "attribute_set"("deleted_at");

-- CreateIndex
CREATE INDEX "attribute_set_group_attribute_set_id_sort_order_idx" ON "attribute_set_group"("attribute_set_id", "sort_order");

-- CreateIndex
CREATE UNIQUE INDEX "attribute_set_group_attribute_set_id_name_key" ON "attribute_set_group"("attribute_set_id", "name");

-- CreateIndex
CREATE INDEX "attribute_set_attribute_group_id_sort_order_idx" ON "attribute_set_attribute"("group_id", "sort_order");

-- CreateIndex
CREATE UNIQUE INDEX "attribute_set_attribute_attribute_set_id_attribute_id_key" ON "attribute_set_attribute"("attribute_set_id", "attribute_id");

-- CreateIndex
CREATE UNIQUE INDEX "product_public_id_key" ON "product"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "product_sku_key" ON "product"("sku");

-- CreateIndex
CREATE INDEX "product_status_deleted_at_idx" ON "product"("status", "deleted_at");

-- CreateIndex
CREATE INDEX "product_attribute_set_id_idx" ON "product"("attribute_set_id");

-- CreateIndex
CREATE INDEX "product_type_idx" ON "product"("type");

-- CreateIndex
CREATE UNIQUE INDEX "product_variant_public_id_key" ON "product_variant"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "product_variant_sku_key" ON "product_variant"("sku");

-- CreateIndex
CREATE INDEX "product_variant_product_id_deleted_at_idx" ON "product_variant"("product_id", "deleted_at");

-- CreateIndex
CREATE INDEX "variant_axis_value_attribute_id_option_id_idx" ON "variant_axis_value"("attribute_id", "option_id");

-- CreateIndex
CREATE UNIQUE INDEX "variant_axis_value_variant_id_attribute_id_key" ON "variant_axis_value"("variant_id", "attribute_id");

-- CreateIndex
CREATE INDEX "product_store_view_store_view_id_idx" ON "product_store_view"("store_view_id");

-- CreateIndex
CREATE UNIQUE INDEX "product_store_view_product_id_store_view_id_key" ON "product_store_view"("product_id", "store_view_id");

-- CreateIndex
CREATE INDEX "product_link_product_id_link_type_idx" ON "product_link"("product_id", "link_type");

-- CreateIndex
CREATE UNIQUE INDEX "product_link_product_id_linked_product_id_link_type_key" ON "product_link"("product_id", "linked_product_id", "link_type");

-- CreateIndex
CREATE INDEX "product_bundle_item_bundle_product_id_sort_order_idx" ON "product_bundle_item"("bundle_product_id", "sort_order");

-- CreateIndex
CREATE INDEX "product_attribute_value_product_id_idx" ON "product_attribute_value"("product_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_pav_scope" ON "product_attribute_value"("product_id", "attribute_id", "scope", "website_id", "store_id", "store_view_id");

-- CreateIndex
CREATE UNIQUE INDEX "category_public_id_key" ON "category"("public_id");

-- CreateIndex
CREATE INDEX "category_parent_id_idx" ON "category"("parent_id");

-- CreateIndex
CREATE INDEX "category_deleted_at_idx" ON "category"("deleted_at");

-- CreateIndex
CREATE INDEX "category_closure_descendant_id_idx" ON "category_closure"("descendant_id");

-- CreateIndex
CREATE UNIQUE INDEX "category_rule_category_id_key" ON "category_rule"("category_id");

-- CreateIndex
CREATE INDEX "product_category_category_id_position_idx" ON "product_category"("category_id", "position");

-- CreateIndex
CREATE UNIQUE INDEX "media_asset_public_id_key" ON "media_asset"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "media_asset_storage_key_key" ON "media_asset"("storage_key");

-- CreateIndex
CREATE INDEX "media_asset_kind_idx" ON "media_asset"("kind");

-- CreateIndex
CREATE INDEX "media_asset_deleted_at_idx" ON "media_asset"("deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "media_transform_asset_id_variant_key" ON "media_transform"("asset_id", "variant");

-- CreateIndex
CREATE INDEX "product_media_product_id_position_idx" ON "product_media"("product_id", "position");

-- CreateIndex
CREATE INDEX "product_media_variant_id_idx" ON "product_media"("variant_id");

-- CreateIndex
CREATE INDEX "product_media_asset_id_idx" ON "product_media"("asset_id");

-- CreateIndex
CREATE INDEX "metafield_definition_owner_type_idx" ON "metafield_definition"("owner_type");

-- CreateIndex
CREATE UNIQUE INDEX "metafield_definition_owner_type_namespace_key_key" ON "metafield_definition"("owner_type", "namespace", "key");

-- CreateIndex
CREATE INDEX "metafield_value_definition_id_owner_id_idx" ON "metafield_value"("definition_id", "owner_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_metafield_ver" ON "metafield_value"("definition_id", "owner_id", "scope", "store_view_id", "language_id", "version");

-- CreateIndex
CREATE UNIQUE INDEX "language_code_key" ON "language"("code");

-- CreateIndex
CREATE UNIQUE INDEX "theme_code_key" ON "theme"("code");

-- CreateIndex
CREATE UNIQUE INDEX "website_public_id_key" ON "website"("public_id");

-- CreateIndex
CREATE UNIQUE INDEX "website_code_key" ON "website"("code");

-- CreateIndex
CREATE INDEX "website_deleted_at_idx" ON "website"("deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "store_public_id_key" ON "store"("public_id");

-- CreateIndex
CREATE INDEX "store_deleted_at_idx" ON "store"("deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "store_website_id_code_key" ON "store"("website_id", "code");

-- CreateIndex
CREATE UNIQUE INDEX "store_view_public_id_key" ON "store_view"("public_id");

-- CreateIndex
CREATE INDEX "store_view_deleted_at_idx" ON "store_view"("deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "store_view_store_id_code_key" ON "store_view"("store_id", "code");

-- AddForeignKey
ALTER TABLE "attribute_option" ADD CONSTRAINT "attribute_option_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "attribute"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attribute_label" ADD CONSTRAINT "attribute_label_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "attribute"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attribute_label" ADD CONSTRAINT "attribute_label_store_view_id_fkey" FOREIGN KEY ("store_view_id") REFERENCES "store_view"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attribute_set_group" ADD CONSTRAINT "attribute_set_group_attribute_set_id_fkey" FOREIGN KEY ("attribute_set_id") REFERENCES "attribute_set"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attribute_set_attribute" ADD CONSTRAINT "attribute_set_attribute_attribute_set_id_fkey" FOREIGN KEY ("attribute_set_id") REFERENCES "attribute_set"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attribute_set_attribute" ADD CONSTRAINT "attribute_set_attribute_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "attribute_set_group"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attribute_set_attribute" ADD CONSTRAINT "attribute_set_attribute_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "attribute"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product" ADD CONSTRAINT "product_attribute_set_id_fkey" FOREIGN KEY ("attribute_set_id") REFERENCES "attribute_set"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_variant" ADD CONSTRAINT "product_variant_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "variant_axis_value" ADD CONSTRAINT "variant_axis_value_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "variant_axis_value" ADD CONSTRAINT "variant_axis_value_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "attribute"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "variant_axis_value" ADD CONSTRAINT "variant_axis_value_option_id_fkey" FOREIGN KEY ("option_id") REFERENCES "attribute_option"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_store_view" ADD CONSTRAINT "product_store_view_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_link" ADD CONSTRAINT "product_link_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_link" ADD CONSTRAINT "product_link_linked_product_id_fkey" FOREIGN KEY ("linked_product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_bundle_item" ADD CONSTRAINT "product_bundle_item_bundle_product_id_fkey" FOREIGN KEY ("bundle_product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_bundle_item" ADD CONSTRAINT "product_bundle_item_component_product_id_fkey" FOREIGN KEY ("component_product_id") REFERENCES "product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_attribute_value" ADD CONSTRAINT "product_attribute_value_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_attribute_value" ADD CONSTRAINT "product_attribute_value_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "attribute"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "category" ADD CONSTRAINT "category_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "category"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "category_closure" ADD CONSTRAINT "category_closure_ancestor_id_fkey" FOREIGN KEY ("ancestor_id") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "category_closure" ADD CONSTRAINT "category_closure_descendant_id_fkey" FOREIGN KEY ("descendant_id") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "category_rule" ADD CONSTRAINT "category_rule_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_category" ADD CONSTRAINT "product_category_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_category" ADD CONSTRAINT "product_category_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "media_transform" ADD CONSTRAINT "media_transform_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "media_asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "media_asset"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "metafield_value" ADD CONSTRAINT "metafield_value_definition_id_fkey" FOREIGN KEY ("definition_id") REFERENCES "metafield_definition"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "website" ADD CONSTRAINT "website_base_currency_fkey" FOREIGN KEY ("base_currency") REFERENCES "currency"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "store" ADD CONSTRAINT "store_website_id_fkey" FOREIGN KEY ("website_id") REFERENCES "website"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "store_view" ADD CONSTRAINT "store_view_store_id_fkey" FOREIGN KEY ("store_id") REFERENCES "store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "store_view" ADD CONSTRAINT "store_view_language_id_fkey" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "store_view" ADD CONSTRAINT "store_view_currency_fkey" FOREIGN KEY ("currency") REFERENCES "currency"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "store_view" ADD CONSTRAINT "store_view_theme_id_fkey" FOREIGN KEY ("theme_id") REFERENCES "theme"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- === Raw blocks Prisma can't express (constraints, triggers, generated cols, NND indexes) ===
-- =============================================================================
-- 0001_foundation_raw.sql
-- Raw-SQL blocks appended to the generated Prisma migration for the Foundation
-- (Store + Catalog core). See plan/02-prisma-schema-and-migrations.md §1 & §5.
--
-- WORKFLOW: run `prisma migrate dev --create-only` to scaffold the base migration,
-- then paste the relevant sections below into that migration.sql (or keep this file
-- and apply it with `prisma db execute --file` right after `migrate deploy` in CI).
-- Everything here is idempotent-friendly where practical.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. Extensions (Prisma also declares these via `extensions=[...]`; safe to repeat)
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

-- -----------------------------------------------------------------------------
-- 1. UUIDv7 generator (time-sortable external ids). Referenced by @default(dbgenerated("uuidv7()"))
--    gen_random_uuid() is core in PostgreSQL 13+.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION uuidv7() RETURNS uuid AS $$
DECLARE
  ts_ms      bigint := (extract(epoch FROM clock_timestamp()) * 1000)::bigint;
  uuid_bytes bytea  := uuid_send(gen_random_uuid());
BEGIN
  -- first 48 bits = unix ms timestamp
  uuid_bytes := overlay(uuid_bytes placing substring(int8send(ts_ms) FROM 3) FROM 1 FOR 6);
  -- version 7 in high nibble of byte 6
  uuid_bytes := set_byte(uuid_bytes, 6, (get_byte(uuid_bytes, 6) & 15) | 112);
  -- RFC-4122 variant in top two bits of byte 8
  uuid_bytes := set_byte(uuid_bytes, 8, (get_byte(uuid_bytes, 8) & 63) | 128);
  RETURN encode(uuid_bytes, 'hex')::uuid;
END;
$$ LANGUAGE plpgsql VOLATILE;

-- -----------------------------------------------------------------------------
-- 2. updated_at trigger (DB-authoritative, so raw-SQL writes also touch it).
--    Prisma's @updatedAt covers ORM writes; this covers everything else.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'theme','website','store','store_view','attribute','attribute_set','product',
    'product_variant','product_attribute_value','category','category_rule',
    'metafield_definition'
  ] LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS trg_set_updated_at ON %I;
       CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON %I
       FOR EACH ROW EXECUTE FUNCTION set_updated_at();', t, t);
  END LOOP;
END $$;

-- -----------------------------------------------------------------------------
-- 3. Deferred / cyclic foreign keys (declared as scalar columns in Prisma to
--    break creation cycles and keep back-relation lists clean).
-- -----------------------------------------------------------------------------
ALTER TABLE website
  ADD CONSTRAINT website_default_store_fk
  FOREIGN KEY (default_store_id) REFERENCES store(id) ON DELETE SET NULL;

ALTER TABLE store
  ADD CONSTRAINT store_root_category_fk
  FOREIGN KEY (root_category_id) REFERENCES category(id) ON DELETE SET NULL;

ALTER TABLE store
  ADD CONSTRAINT store_default_store_view_fk
  FOREIGN KEY (default_store_view_id) REFERENCES store_view(id) ON DELETE SET NULL;

-- Scope FKs on value / override tables (kept scalar in Prisma).
ALTER TABLE product_attribute_value
  ADD CONSTRAINT pav_website_fk    FOREIGN KEY (website_id)    REFERENCES website(id)    ON DELETE CASCADE,
  ADD CONSTRAINT pav_store_fk      FOREIGN KEY (store_id)      REFERENCES store(id)      ON DELETE CASCADE,
  ADD CONSTRAINT pav_store_view_fk FOREIGN KEY (store_view_id) REFERENCES store_view(id) ON DELETE CASCADE;

ALTER TABLE product_store_view
  ADD CONSTRAINT psv_store_view_fk FOREIGN KEY (store_view_id) REFERENCES store_view(id) ON DELETE CASCADE;

ALTER TABLE product_media
  ADD CONSTRAINT pm_store_view_fk  FOREIGN KEY (store_view_id) REFERENCES store_view(id) ON DELETE SET NULL;

ALTER TABLE metafield_value
  ADD CONSTRAINT mv_website_fk     FOREIGN KEY (website_id)    REFERENCES website(id)    ON DELETE CASCADE,
  ADD CONSTRAINT mv_store_fk       FOREIGN KEY (store_id)      REFERENCES store(id)      ON DELETE CASCADE,
  ADD CONSTRAINT mv_store_view_fk  FOREIGN KEY (store_view_id) REFERENCES store_view(id) ON DELETE CASCADE,
  ADD CONSTRAINT mv_language_fk    FOREIGN KEY (language_id)   REFERENCES language(id)   ON DELETE SET NULL;

-- -----------------------------------------------------------------------------
-- 4. Scope-consistency CHECK constraints (exactly the right *_id set per scope).
--    This is what replaces Magento's "store_id = 0 means default" convention.
-- -----------------------------------------------------------------------------
ALTER TABLE product_attribute_value
  ADD CONSTRAINT pav_scope_consistent CHECK (
    (scope = 'GLOBAL'     AND website_id IS NULL     AND store_id IS NULL     AND store_view_id IS NULL) OR
    (scope = 'WEBSITE'    AND website_id IS NOT NULL AND store_id IS NULL     AND store_view_id IS NULL) OR
    (scope = 'STORE'      AND store_id   IS NOT NULL AND store_view_id IS NULL) OR
    (scope = 'STORE_VIEW' AND store_view_id IS NOT NULL)
  ),
  -- at least one typed value column populated
  ADD CONSTRAINT pav_value_present CHECK (
    num_nonnulls(value_text, value_int, value_decimal, value_datetime, value_json) >= 1
  );

ALTER TABLE metafield_value
  ADD CONSTRAINT mv_scope_consistent CHECK (
    (scope = 'GLOBAL'     AND website_id IS NULL     AND store_id IS NULL     AND store_view_id IS NULL) OR
    (scope = 'WEBSITE'    AND website_id IS NOT NULL AND store_id IS NULL     AND store_view_id IS NULL) OR
    (scope = 'STORE'      AND store_id   IS NOT NULL AND store_view_id IS NULL) OR
    (scope = 'STORE_VIEW' AND store_view_id IS NOT NULL)
  );

-- -----------------------------------------------------------------------------
-- 5. scope_rank generated column (single-pass scope resolution; see plan 02 §5).
--    0=GLOBAL .. 3=STORE_VIEW ; DISTINCT ON (attribute_id) ORDER BY scope_rank DESC.
-- -----------------------------------------------------------------------------
ALTER TABLE product_attribute_value
  ADD COLUMN scope_rank smallint GENERATED ALWAYS AS (
    CASE scope
      WHEN 'GLOBAL'     THEN 0
      WHEN 'WEBSITE'    THEN 1
      WHEN 'STORE'      THEN 2
      WHEN 'STORE_VIEW' THEN 3
    END
  ) STORED;

-- -----------------------------------------------------------------------------
-- 6. Fix scope uniqueness: NULLs must NOT be distinct, else duplicate GLOBAL rows
--    slip through (Postgres treats NULLs as distinct by default). PG15+.
--    Replace the Prisma-generated unique constraints with NULLS NOT DISTINCT ones.
-- -----------------------------------------------------------------------------
-- Prisma may emit @@unique(map:) as either a CONSTRAINT or a plain unique INDEX
-- depending on version; drop whichever exists before recreating with NULLS NOT DISTINCT.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_pav_scope') THEN
    ALTER TABLE product_attribute_value DROP CONSTRAINT uq_pav_scope;
  ELSIF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'uq_pav_scope' AND relkind = 'i') THEN
    DROP INDEX uq_pav_scope;
  END IF;
END $$;
CREATE UNIQUE INDEX uq_pav_scope
  ON product_attribute_value (product_id, attribute_id, scope, website_id, store_id, store_view_id)
  NULLS NOT DISTINCT;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_metafield_ver') THEN
    ALTER TABLE metafield_value DROP CONSTRAINT uq_metafield_ver;
  ELSIF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'uq_metafield_ver' AND relkind = 'i') THEN
    DROP INDEX uq_metafield_ver;
  END IF;
END $$;
CREATE UNIQUE INDEX uq_metafield_ver
  ON metafield_value (definition_id, owner_id, scope, store_view_id, language_id, version)
  NULLS NOT DISTINCT;

-- -----------------------------------------------------------------------------
-- 7. Single-default enforcement (exactly one default website / attribute_set).
-- -----------------------------------------------------------------------------
CREATE UNIQUE INDEX uq_one_default_website
  ON website (is_default) WHERE is_default AND deleted_at IS NULL;

CREATE UNIQUE INDEX uq_one_default_attribute_set
  ON attribute_set (is_default) WHERE is_default AND deleted_at IS NULL;

-- -----------------------------------------------------------------------------
-- 8. Layered-navigation / faceting indexes on the EAV value table.
--    (DB is the correct source of truth; OpenSearch is the fast facet path.)
-- -----------------------------------------------------------------------------
CREATE INDEX ix_pav_attr_int
  ON product_attribute_value (attribute_id, value_int) WHERE value_int IS NOT NULL;

CREATE INDEX ix_pav_attr_decimal
  ON product_attribute_value (attribute_id, value_decimal) WHERE value_decimal IS NOT NULL;

CREATE INDEX ix_pav_value_json
  ON product_attribute_value USING gin (value_json jsonb_path_ops) WHERE value_json IS NOT NULL;

-- PDP hydration + single-pass scope resolution
CREATE INDEX ix_pav_resolve
  ON product_attribute_value (product_id, attribute_id, scope_rank DESC);

-- -----------------------------------------------------------------------------
-- 9. JSONB GIN indexes (rules / config / metafields).
-- -----------------------------------------------------------------------------
CREATE INDEX ix_category_rule_gin      ON category_rule       USING gin (rule jsonb_path_ops);
CREATE INDEX ix_metafield_value_gin    ON metafield_value     USING gin (value jsonb_path_ops);
CREATE INDEX ix_attribute_validation_gin ON attribute         USING gin (validation_rules jsonb_path_ops);

-- -----------------------------------------------------------------------------
-- 10. Category LTREE indexes + partial "active" indexes.
-- -----------------------------------------------------------------------------
CREATE INDEX ix_category_path_gist  ON category USING gist (path);
CREATE INDEX ix_category_path_btree ON category USING btree (path);

-- Hot-path partial indexes (soft-delete aware). Prisma's plain @@index([deletedAt])
-- stays; these give the planner selective active-only paths.
CREATE INDEX ix_product_active      ON product     (status)          WHERE deleted_at IS NULL;
CREATE INDEX ix_variant_active      ON product_variant (product_id)  WHERE deleted_at IS NULL;
CREATE INDEX ix_category_active     ON category    (parent_id)       WHERE deleted_at IS NULL;

-- Admin fuzzy search on cached product name
CREATE INDEX ix_product_name_trgm   ON product USING gin (name_default gin_trgm_ops);

-- -----------------------------------------------------------------------------
-- 11. Category path + closure maintenance (INSERT). Reparenting goes through the
--     category_reparent(child, new_parent) service function (see §12).
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION category_before_insert() RETURNS trigger AS $$
BEGIN
  IF NEW.parent_id IS NULL THEN
    NEW.path := NEW.id::text::ltree;
  ELSE
    SELECT path || NEW.id::text INTO NEW.path FROM category WHERE id = NEW.parent_id;
    IF NEW.path IS NULL THEN
      RAISE EXCEPTION 'parent category % has no path (missing/uninitialized)', NEW.parent_id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION category_after_insert() RETURNS trigger AS $$
BEGIN
  -- self reference
  INSERT INTO category_closure (ancestor_id, descendant_id, depth)
  VALUES (NEW.id, NEW.id, 0);
  -- all ancestors of the parent, +1 depth
  IF NEW.parent_id IS NOT NULL THEN
    INSERT INTO category_closure (ancestor_id, descendant_id, depth)
    SELECT ancestor_id, NEW.id, depth + 1
    FROM category_closure
    WHERE descendant_id = NEW.parent_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_category_before_insert ON category;
CREATE TRIGGER trg_category_before_insert
  BEFORE INSERT ON category
  FOR EACH ROW EXECUTE FUNCTION category_before_insert();

DROP TRIGGER IF EXISTS trg_category_after_insert ON category;
CREATE TRIGGER trg_category_after_insert
  AFTER INSERT ON category
  FOR EACH ROW EXECUTE FUNCTION category_after_insert();

-- -----------------------------------------------------------------------------
-- 12. Reparent helper (recomputes path + closure for a moved subtree).
--     Call from the application inside a transaction; keeps moves correct & atomic.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION category_reparent(p_child bigint, p_new_parent bigint)
RETURNS void AS $$
DECLARE
  new_base ltree;
  old_path ltree;
BEGIN
  SELECT path INTO old_path FROM category WHERE id = p_child;
  IF p_new_parent IS NULL THEN
    new_base := p_child::text::ltree;
  ELSE
    SELECT path || p_child::text INTO new_base FROM category WHERE id = p_new_parent;
  END IF;

  -- rewrite paths of the subtree
  UPDATE category
     SET path = new_base || subpath(path, nlevel(old_path))
   WHERE path <@ old_path AND id <> p_child;
  UPDATE category SET path = new_base, parent_id = p_new_parent WHERE id = p_child;

  -- rebuild closure for the subtree: drop links from outside-ancestors into subtree...
  DELETE FROM category_closure
   WHERE descendant_id IN (SELECT id FROM category WHERE path <@ new_base)
     AND ancestor_id  NOT IN (SELECT id FROM category WHERE path <@ new_base);
  -- ...then re-link new ancestors × subtree
  INSERT INTO category_closure (ancestor_id, descendant_id, depth)
  SELECT a.ancestor_id, d.descendant_id, a.depth + d.depth + 1
  FROM category_closure a
  CROSS JOIN category_closure d
  WHERE a.descendant_id = p_new_parent
    AND d.ancestor_id  = p_child
  ON CONFLICT DO NOTHING;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- End 0001_foundation_raw.sql
-- =============================================================================
